// Code generated by "stringer -type=PrinceTypeInt -linecomment"; DO NOT EDIT.

package stringer_test

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[BOOL-10]
	_ = x[INT64-20]
	_ = x[TestComentHaveOther-30]
	_ = x[TestNotComment-40]
}

const (
	_PrinceTypeInt_name_0 = "prince-INVALID"
	_PrinceTypeInt_name_1 = "prince-BOOL"
	_PrinceTypeInt_name_2 = "prince-INT64"
	_PrinceTypeInt_name_3 = "prince-_v%.&*TestComentHaveOther"
	_PrinceTypeInt_name_4 = "TestNotComment"
)

func (i PrinceTypeInt) String() string {
	switch {
	case i == 0:
		return _PrinceTypeInt_name_0
	case i == 10:
		return _PrinceTypeInt_name_1
	case i == 20:
		return _PrinceTypeInt_name_2
	case i == 30:
		return _PrinceTypeInt_name_3
	case i == 40:
		return _PrinceTypeInt_name_4
	default:
		return "PrinceTypeInt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
