// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package demogrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DemogrpcClient is the client API for Demogrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DemogrpcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type demogrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewDemogrpcClient(cc grpc.ClientConnInterface) DemogrpcClient {
	return &demogrpcClient{cc}
}

func (c *demogrpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/demogrpc.Demogrpc/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemogrpcServer is the server API for Demogrpc service.
// All implementations must embed UnimplementedDemogrpcServer
// for forward compatibility
type DemogrpcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedDemogrpcServer()
}

// UnimplementedDemogrpcServer must be embedded to have forward compatible implementations.
type UnimplementedDemogrpcServer struct {
}

func (UnimplementedDemogrpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDemogrpcServer) mustEmbedUnimplementedDemogrpcServer() {}

// UnsafeDemogrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemogrpcServer will
// result in compilation errors.
type UnsafeDemogrpcServer interface {
	mustEmbedUnimplementedDemogrpcServer()
}

func RegisterDemogrpcServer(s grpc.ServiceRegistrar, srv DemogrpcServer) {
	s.RegisterService(&Demogrpc_ServiceDesc, srv)
}

func _Demogrpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemogrpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/demogrpc.Demogrpc/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemogrpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Demogrpc_ServiceDesc is the grpc.ServiceDesc for Demogrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Demogrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demogrpc.Demogrpc",
	HandlerType: (*DemogrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Demogrpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demogrpc.proto",
}
