// Code generated by "stringer -type=Type -linecomment"; DO NOT EDIT.

package attr_test

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[BOOL-1]
	_ = x[INT64-2]
	_ = x[FLOAT64-3]
	_ = x[STRING-4]
	_ = x[BOOLSLICE-5]
	_ = x[INT64SLICE-6]
	_ = x[FLOAT64SLICE-7]
	_ = x[STRINGSLICE-8]
}

const _Type_name = "prince-INVALIDprince-BOOLprince-INT64prince-FLOAT64prince-STRINGprince-BOOLSLICEprince-INT64SLICEprince-FLOAT64SLICEprince-STRINGSLICE"

var _Type_index = [...]uint8{0, 14, 25, 37, 51, 64, 80, 97, 116, 134}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
