// Code generated by goctl. DO NOT EDIT.
// Source: demogrpc.proto

package server

import (
	"context"

	"gozero-demo/demogrpc/demogrpc"
	"gozero-demo/demogrpc/internal/logic"
	"gozero-demo/demogrpc/internal/svc"
)

type DemogrpcServer struct {
	svcCtx *svc.ServiceContext
	demogrpc.UnimplementedDemogrpcServer
}

func NewDemogrpcServer(svcCtx *svc.ServiceContext) *DemogrpcServer {
	return &DemogrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *DemogrpcServer) Ping(ctx context.Context, in *demogrpc.Request) (*demogrpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
