WebPageUrlList:
  https://www.xxx.cn/xxx
FTP:
  Conf:
    Host: xx.xx.xx.xx
    Port: 21
    Username: xxx
    Password: xxx
  AccessHost: https://xxx.xxx.cn
  PathPrefix: programUpload

TargetImgHost: https://xxx.com