Env: dev
AppName: ticket-xxx-yyy-zzz
Port: 8080
LogPath: ./logs/
LogLevel: 5
IsBothStdout: true

Website:
  LoginUrl: https://xxxx.com/agentadmin/Login.aspx
  LoginUserName: xxxx
  LoginPassword: yyyy

ListenNetwork:
  Order:
    Url: https://yyyy.com/agentadmin/offline/SupplierHandler.ashx
    NewOrderBodyContains: <tr
    SaveNewOrderInfo:
      FilePath: ./data
      FileName: order_%s.dt
      IsAppend: true

